---
title: "Drunk Passenger Problem"
author: "Yuchan Jeong"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
dpseat = function(n) {
    Seat = 1:n # set the seats on the plane
    S = sample(Seat,1) # S is the drunk passenger and by sample(Seat,1) function he would choose one of the seat from 1 to 100
  
  if (S==1) { # If Drunk passenger chose #1 seat, then last passenger successes to take designated seat
    return (1) # 1 indicates last passenger successes to take designated seat
  }
  else if (S==n) { # n is the last seat. If Drunk passenger takes it, last passenger fails
    return (0) # 0 indicates last passenger fails to take designated seat
  }
  else { # If a drunk passenger takes another seat, we have to repeat the process until one of the passengers takes either seat #1 or the last seat, which concludes the case.
    Seat = Seat[-which(Seat==S)] # If someone takes a seat, the seat is taken out of the options
    
    for (i in 2:n-1) { # The drunk passenger has already chosen their seat, and the last passenger must wait until the other passengers finish the process.
      S = sample(Seat,1)
      
      if (S==1) {
        return(1)
      }
      
      else if (S==n) {
        return(0)
      }
      else {
        Seat = Seat[-which(Seat==S)] 
      }
    }
  }
  S = sample(Seat, 1)
  
  if (S==n) {
    return (1)
  }
  
  else {
    return (0)
  }
}
```

```{r}
N_seat = 100 # Number of Seats
trials = 100000 # Number of Trials

df = print(replicate(trials, dpseat(N_seat))) #Replicate the above function with 100,000 trials to approximate the experimental probability closer to the theoretical probability, which we found to be 1/2

dff = data.frame(df)

num_zeros = sum(dff == 0)
num_ones = sum(dff == 1)
```

```
0 indicates the result of the last passenger failing to sit in their designated seat, while 1 indicates the result of the last passenger succeeding in sitting in their designated seat.
```
```{r}
cat('0:',num_zeros, '1:',num_ones)
```

```{r}
cat('The probability of last person it his own seat:', round(mean(df),2))
```
